# Generated by Django 4.2.7 on 2024-05-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinderpro', '0002_alter_room_floor_alter_room_x_alter_room_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.AddField(
            model_name='room',
            name='floorNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
