# Generated by Django 4.2.13 on 2024-05-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinderpro', '0004_alter_room_floornumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('college', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, unique=True)),
                ('slug', models.SlugField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(default='Rizal Hall', max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='college',
            field=models.CharField(default='College of Arts and Sciences', max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
