# Generated by Django 4.2.7 on 2024-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinderpro', '0004_alter_room_floornumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
