# Generated by Django 4.2.7 on 2024-05-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinderpro', '0005_room_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('college', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(max_length=300, null=True)),
            ],
        ),
    ]
