# Generated by Django 4.2.7 on 2024-05-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinderpro', '0007_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='college',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
